version: '3'
services:
  shadowsocks:
    
    ports:
      - 80:8080
     
 
    build:
      context: .
        
      dockerfile: Dockerfile
    environment:
      - METHOD=aes-256-gcm # 加密方法
      - PASSWORD=170826  # 密码
   
    restart: always