obfs_tls:
    container_name: obfs_tls
    image: mydocker/simple-obfs:latest
    ports:
      - 443:8139
    environment:
      - OBFS_OPTS=tls
      - FORWARD=shadowsocks:8388
      - FAILOVER=baidu.com:443
      - ARGS=--mptcp
    depends_on:
      - shadowsocks
    restart: always
    networks:
      - ssnet

  shadowsocks:
    container_name: shadowsocks
    image: shadowsocks/shadowsocks-libev:v3.2.3
    expose:
      - 8388/tcp
      - 8388/udp
    environment:
      - PASSWORD=f**kgfw
      - METHOD=xchacha20-ietf-poly1305
      - TIMEOUT=1800
      - DNS_ADDRS=8.8.8.8,1.1.1.1
      - ARGS=--mptcp --no-delay
    restart: always
    networks:
      - ssnet